// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"strings"

	"github.com/gorilla/mux"
	"github.com/jacobbrewer1/uhttp"
	"github.com/jacobbrewer1/uhttp/common"
	"github.com/jacobbrewer1/web"
	"github.com/jacobbrewer1/web/logging"
	"github.com/jacobbrewer1/web/metrics"
	openapi_types "github.com/oapi-codegen/runtime/types"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	admissionv1 "k8s.io/api/admission/v1"
)

// PostMutateJSONBody defines parameters for PostMutate.
type PostMutateJSONBody = *admissionv1.AdmissionReview

// PostMutateJSONRequestBody defines body for PostMutate for application/json ContentType.
type PostMutateJSONRequestBody = PostMutateJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostMutateWithBody request with any body
	PostMutateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostMutate(ctx context.Context, body PostMutateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostMutateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMutateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMutate(ctx context.Context, body PostMutateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMutateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostMutateRequest calls the generic PostMutate builder with application/json body
func NewPostMutateRequest(server string, body PostMutateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostMutateRequestWithBody(server, "application/json", bodyReader)
}

// NewPostMutateRequestWithBody generates requests for PostMutate with any type of body
func NewPostMutateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mutate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostMutateWithBodyWithResponse request with any body
	PostMutateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMutateResponse, error)

	PostMutateWithResponse(ctx context.Context, body PostMutateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMutateResponse, error)
}

type PostMutateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *admissionv1.AdmissionReview
}

// Status returns HTTPResponse.Status
func (r PostMutateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostMutateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostMutateWithBodyWithResponse request with arbitrary body returning *PostMutateResponse
func (c *ClientWithResponses) PostMutateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMutateResponse, error) {
	rsp, err := c.PostMutateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMutateResponse(rsp)
}

func (c *ClientWithResponses) PostMutateWithResponse(ctx context.Context, body PostMutateJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMutateResponse, error) {
	rsp, err := c.PostMutate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMutateResponse(rsp)
}

// ParsePostMutateResponse parses an HTTP response from a PostMutateWithResponse call
func ParsePostMutateResponse(rsp *http.Response) (*PostMutateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostMutateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest admissionv1.AdmissionReview
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostMutate (POST /mutate)
	// Mutate incoming pod definition
	PostMutate(ctx context.Context, l *slog.Logger, r *http.Request, body0 *PostMutateJSONBody) (*admissionv1.AdmissionReview, error)
}

const (
	loggingKeyError = "err"
)

var (
	// TotalRequests is a counter for the total number of requests by ALL operations.
	TotalRequests = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "total_requests",
		Help: "Total number of requests",
	}, []string{"code", "method"})

	// PostMutateTotalRequests is a counter for the total number of requests for PostMutate.
	PostMutateTotalRequests = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "postmutate_total_requests",
		Help: "Total number of requests for PostMutate",
	}, []string{"code", "method"})

	// PostMutateRequestDuration is a histogram for the request duration for PostMutate.
	PostMutateRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "postmutate_request_duration_seconds",
		Help:    "Request duration in seconds for PostMutate",
		Buckets: prometheus.DefBuckets,
	}, []string{"code", "method"})

	// PostMutateRequestSize is a histogram for the request size for PostMutate.
	PostMutateRequestSize = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "postmutate_request_size_bytes",
		Help:    "Request size in bytes for PostMutate",
		Buckets: prometheus.DefBuckets,
	}, []string{"code", "method"})

	// PostMutateResponseSize is a histogram for the response size for PostMutate.
	PostMutateResponseSize = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "postmutate_response_size_bytes",
		Help:    "Response size in bytes for PostMutate",
		Buckets: prometheus.DefBuckets,
	}, []string{"code", "method"})
)

type RateLimiterFunc = func(context.Context, *http.Request) bool
type ErrorHandlerFunc = func(context.Context, *slog.Logger, http.ResponseWriter, error)

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	l *slog.Logger

	authz       ServerInterface
	handler     ServerInterface
	rateLimiter RateLimiterFunc

	errorHandlerFunc ErrorHandlerFunc
	isInternalAPI    bool
}

// WithLogger sets the logger for the server.
func WithLogger(l *slog.Logger) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.l = l
	}
}

// WithAuthorization applies the passed authorization middleware to the server.
func WithAuthorization(authz ServerInterface) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.authz = authz
	}
}

// WithRateLimiter applies the rate limiter middleware to routes with x-global-rate-limit.
func WithRateLimiter(rateLimiter RateLimiterFunc) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.rateLimiter = rateLimiter
	}
}

// WithErrorHandlerFunc sets the error handler function for the server.
func WithErrorHandlerFunc(errorHandlerFunc ErrorHandlerFunc) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.errorHandlerFunc = errorHandlerFunc
	}
}

// WithInternalAPI sets the server as an internal API.
func WithInternalAPI(isInternalAPI bool) ServerOption {
	return func(s *ServerInterfaceWrapper) {
		s.isInternalAPI = isInternalAPI
	}
}

// ServerOption represents an optional feature applied to the server.
type ServerOption func(s *ServerInterfaceWrapper)

// PostMutate operation middleware
func (siw *ServerInterfaceWrapper) PostMutate(w http.ResponseWriter, r *http.Request) {
	l := logging.LoggerFromRequest(siw.l, r)
	l = l.With(
		slog.String(logging.KeyHandler, "PostMutate"),
	)

	ctx := r.Context()
	w = uhttp.NewResponseWriter(w,
		uhttp.WithDefaultStatusCode(http.StatusOK),
		uhttp.WithDefaultHeader(uhttp.HeaderRequestID, uhttp.RequestIDFromContext(ctx)),
		uhttp.WithDefaultHeader(uhttp.HeaderContentType, "application/json; charset=utf-8"),
	)

	// ------------- Body parameter for PostMutate for application/json ContentType -------------
	jsonBody := new(PostMutateJSONRequestBody)
	if err := siw.parseRequestBody(r, "application/json", jsonBody); err != nil {
		siw.errorHandlerFunc(ctx, l, w, err)
		return
	} else if jsonBody == nil {
		siw.errorHandlerFunc(ctx, l, w, &UnmarshalingBodyError{Err: errors.New("empty body")})
		return
	}

	// Convert the request body type to the server handler type
	body := (*PostMutateJSONBody)(jsonBody)

	if siw.rateLimiter != nil {
		if !siw.rateLimiter(ctx, r) {
			encodeErrorResponse(w, &uhttp.HTTPError{
				ErrorMessage: common.ErrorMessage{
					Title:     http.StatusText(http.StatusTooManyRequests),
					Detail:    "Rate limit exceeded",
					Status:    http.StatusTooManyRequests,
					RequestId: uhttp.RequestIDFromContext(ctx),
					Details: []any{
						"Rate limit exceeded",
					},
				},
			})
			return
		}
	}

	// Invoke the callback with all the unmarshalled arguments
	resp, err := siw.handler.PostMutate(ctx, logging.LoggerWithComponent(l, "handler"), r, body)
	if err != nil {
		siw.errorHandlerFunc(ctx, l, w, err)
		return
	}

	w.Header().Set(uhttp.HeaderContentType, "application/json; charset=utf-8")
	w.WriteHeader(200)
	err = json.NewEncoder(w).Encode(resp)
	if err != nil {
		siw.errorHandlerFunc(ctx, l, w, err)
		return
	}
}

// parseRequestBody parses the request body into the expected type.
func (siw *ServerInterfaceWrapper) parseRequestBody(r *http.Request, contentType string, dest any) error {
	if r.Body == http.NoBody {
		return &UnmarshalingBodyError{Err: errors.New("empty body")}
	}

	switch contentType {
	case "application/json":
		decoder := json.NewDecoder(r.Body)
		if !siw.isInternalAPI {
			decoder.DisallowUnknownFields()
		}
		if err := decoder.Decode(dest); err != nil {
			e := new(uhttp.HTTPError)
			if errors.As(err, &e) {
				return err
			}
			return &UnmarshalingBodyError{Err: err}
		}
	case "application/x-www-form-urlencoded":
		bdy, err := io.ReadAll(r.Body)
		if err != nil {
			e := new(uhttp.HTTPError)
			if errors.As(err, &e) {
				return err
			}
			return &UnmarshalingBodyError{Err: err}
		}

		body, ok := dest.(*openapi_types.File)
		if !ok {
			e := new(uhttp.HTTPError)
			if errors.As(err, &e) {
				return err
			}
			return &UnmarshalingBodyError{Err: fmt.Errorf("expected *openapi_types.FormData, got %T", dest)}
		}

		body.InitFromBytes(bdy, "file")
	default:
		return &UnsupportedContentTypeError{ContentType: contentType}
	}

	return nil
}

// handleError handles returning a correctly-formatted error to the API caller.
func handleError(ctx context.Context, l *slog.Logger, w http.ResponseWriter, err error) {
	l.Error("Error handling request", slog.String(loggingKeyError, err.Error()))

	e := new(uhttp.HTTPError)
	if errors.As(err, &e) {
		e.RequestId = uhttp.RequestIDFromContext(ctx)
		_ = encodeErrorResponse(w, e)
		return
	}

	code := http.StatusInternalServerError
	if e, ok := err.(uhttp.StatusCoder); ok {
		code = e.StatusCode()
	}

	_ = encodeErrorResponse(w, &uhttp.HTTPError{
		ErrorMessage: common.ErrorMessage{
			Title:     http.StatusText(code),
			Detail:    "error handling request",
			Status:    code,
			RequestId: uhttp.RequestIDFromContext(ctx),
			Details: []any{
				err.Error(),
			},
		},
	})
}

// encodeErrorResponse encodes input response as an RFC-7807-compliant response to w.
func encodeErrorResponse(w http.ResponseWriter, response any) error {
	w.Header().Set(uhttp.HeaderContentType, "application/problem+json; charset=utf-8")

	if e, ok := response.(uhttp.StatusCoder); ok {
		w.WriteHeader(e.StatusCode())
	}

	return json.NewEncoder(w).Encode(response)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnsupportedContentTypeError struct {
	ContentType string
}

func (e *UnsupportedContentTypeError) StatusCode() int {
	return http.StatusUnsupportedMediaType
}

func (e *UnsupportedContentTypeError) Error() string {
	return fmt.Sprintf("Unsupported content type: %s", e.ContentType)
}

type UnmarshalingBodyError struct {
	Err error
}

func (e *UnmarshalingBodyError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *UnmarshalingBodyError) Error() string {
	return fmt.Sprintf("Error unmarshaling request body: %s", e.Err.Error())
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) StatusCode() int {
	return http.StatusBadRequest
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// RegisterUnauthedHandlers registers any api handlers which do not have any authentication on them. Most services will not have any.
func RegisterUnauthedHandlers(router *mux.Router, si ServerInterface, opts ...ServerOption) {
	wrapper := ServerInterfaceWrapper{
		l:                slog.Default(),
		authz:            nil,
		handler:          si,
		rateLimiter:      nil,
		errorHandlerFunc: handleError,
	}

	for _, opt := range opts {
		if opt == nil {
			continue
		}
		opt(&wrapper)
	}

	router.Use(uhttp.AuthHeaderToContextMux())
	router.Use(uhttp.GenerateOrCopyRequestIDMux())

	router.Methods(http.MethodPost).
		Path("/mutate").
		Handler(web.WrapHandler(
			wrapper.PostMutate,
			metrics.InstrumentCounter(TotalRequests),
			metrics.InstrumentCounter(PostMutateTotalRequests),
			metrics.InstrumentDuration(PostMutateRequestDuration),
			uhttp.InstrumentRequestSize(PostMutateRequestSize),
			metrics.InstrumentResponseSize(PostMutateResponseSize),
		))
}
