load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("//tools/bazel/oci:build_container.bzl", "build_container")

go_library(
    name = "kube-mutating-webhook_lib",
    srcs = [
        "main.go",
        "pem.go",
    ],
    importpath = "github.com/jacobbrewer1/kubernetes-mutating-webhook/cmd/kube-mutating-webhook",
    visibility = ["//visibility:private"],
    deps = [
        "//cmd/kube-mutating-webhook/api/openapi",
        "//cmd/kube-mutating-webhook/service",
        "@com_github_gorilla_mux//:mux",
        "@com_github_jacobbrewer1_web//:web",
        "@com_github_jacobbrewer1_web//k8s",
        "@com_github_jacobbrewer1_web//logging",
        "@com_github_spf13_viper//:viper",
        "@io_k8s_api//admissionregistration/v1:admissionregistration",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
    ],
)

go_binary(
    name = "kube-mutating-webhook",
    embed = [":kube-mutating-webhook_lib"],
    visibility = ["//visibility:public"],
)

build_container("kube-mutating-webhook")
